image:
  repository: docker.elastic.co/elasticsearch/elasticsearch-oss
  tag: "6.4.0"
  pullPolicy: IfNotPresent
master:
  persistence:
    storageClass: dev-es-master-persistence
data:
  replicas: 3
  persistence:
    storageClass: dev-es-data-persistence
client:
  replicas: 1
  serviceType: NodePort
  nodePort: 30200